# Generated by Django 4.2 on 2023-04-13 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProjectName', models.CharField(max_length=200)),
                ('Reason', models.CharField(max_length=200)),
                ('Type', models.CharField(max_length=200)),
                ('Division', models.CharField(max_length=200)),
                ('Category', models.CharField(max_length=200)),
                ('Priority', models.CharField(max_length=200)),
                ('Dept', models.CharField(max_length=200)),
                ('Location', models.CharField(max_length=200)),
                ('Status', models.CharField(max_length=200)),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
            ],
        ),
    ]
